# Generated by Django 4.2.30 on 2026-05-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('glucose', models.FloatField()),
                ('haemoglobin', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
